---
# tomcat handlers
- name: Restart tomcat
  service: name={{ tomcat_service }} state=restarted

- name: Restart nginx
  service: name={{ nginix_service }} state=restarted

- name: Restart zabbix-agent
  service: name {{ zabbix_agent }} state=restarted
