# tomcat.yml
---
- name: Install tomcat playbook
  hosts: tomcat
  remote_user: ubuntu
  vars:
    admin_user: "admin"
    admin_password: "admin"
    SERVER_NAME: "{{ ansible_host }}"
    PORT_NUMBER: "8080"

  tasks:
    - name: Install tomcat packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - tomcat7
        - tomcat7-admin

    - name: Copy tomcat server config file
      template: src=files/server.xml.j2 dest=/etc/tomcat7/server.xml
      notify: Restart tomcat

    - name: Copy tomcat users config file
      template: src=files/tomcat-users.xml.j2 dest=/etc/tomcat7/tomcat-users.xml
      notify: Restart tomcat

#    - name: Upload war
#      copy: src=files/hello-world.war dest=/var/lib/tomcat7/webapps/hello-world.war owner=tomcat7 group=tomcat7
#      notify: Restart tomcat

    - meta: flush_handlers

    - name: Ensure tomcat is started and enabled
      service: name=tomcat7 state=started enabled=yes

    - name: Check if tomcat manager is up
      uri: url="http://{{ ansible_host }}:8080/manager/html" user={{ admin_user }} password={{ admin_password }}
      register: result
      until: result.status == 200
      retries: 10

    - name: Update apt cache
      apt: update_cache=yes
      become: true

    - name: Install required packages
      apt: name=nginx
      become: true

    - name: copy nginix support files
      template: src=files/{{ item }}.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
      with_items:
        - local
      become: true
      notify: Restart nginx

    - meta: flush_handlers

    - name: Ensure nginx is started and enabled
      service: name=nginx state=started enabled=yes

  handlers:
    - name: Restart tomcat
      service: name=tomcat7 state=restarted
    - name: Restart nginx
      service: name=nginx state=restarted
