Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision 'python', type: 'shell', inline: 'apt-get install python-minimal -y'
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
  end

  # ubuntu node VM
  config.vm.define 'node01' do |node01|
    node01.vm.hostname = 'node01.local'
    node01.vm.network :private_network, ip: '192.168.13.114'
  end
end
