---
- name: Install tomcat playbook
  hosts: node01
  vars:
    admin_user: "admin"
    admin_password: "admin"

  tasks:
    - name: Install epel repo
      package: name=epel-release state=installed

    - name: Install tomcat packages
      yum: name={{ item }} state=installed
      with_items:
        - tomcat
        - tomcat-admin-webapps

    - name: Copy tomcat server config file
      template: src=files/server.xml.j2 dest=/etc/tomcat/server.xml
      notify: Restart tomcat

    - name: Copy tomcat users config file
      template: src=files/tomcat-users.xml.j2 dest=/etc/tomcat/tomcat-users.xml
      notify: Restart tomcat

    - name: Upload war
      copy: src=files/hello-world.war dest=/var/lib/tomcat/webapps/hello-world.war owner=tomcat group=tomcat
      notify: Restart tomcat

    - meta: flush_handlers

    - name: Ensure tomcat is started and enabled
      service: name=tomcat state=started enabled=yes

    - name: Check if tomcat manager is up
      uri: url="http://{{ ansible_host }}:8080/manager/html" user={{ admin_user }} password={{ admin_password }}
      register: result
      until: result.status == 200
      retries: 5

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
